
package veterinaria_Alkhovet;

import formulario.JFCliente;
import formulario.JFCompra;
import formulario.JFProducto;
import formulario.JFProveedor;
import formulario.JFJuego;
import formulario.JFVenta;
import formulario.JFVeterinario;



public class Veterinaria extends javax.swing.JFrame {

    
    public Veterinaria() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("Veterinaria ALKHOVET");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrar = new rojeru_san.RSButton();
        btnProductos = new rojeru_san.RSButton();
        btnJuegos = new rojeru_san.RSButton();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        rSPanelImage2 = new rojerusan.RSPanelImage();
        rSPanelImage3 = new rojerusan.RSPanelImage();
        rSPanelImage4 = new rojerusan.RSPanelImage();
        btnCerrar = new rojeru_san.RSButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setExtendedState(MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(1050, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setBackground(new java.awt.Color(4, 74, 138));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 150, 50));

        btnProductos.setBackground(new java.awt.Color(4, 74, 138));
        btnProductos.setText("Productos");
        btnProductos.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 160, 50));

        btnJuegos.setBackground(new java.awt.Color(4, 74, 138));
        btnJuegos.setText("Juegos");
        btnJuegos.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        btnJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegosActionPerformed(evt);
            }
        });
        getContentPane().add(btnJuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, 170, 50));

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imagenes/register-icon-@2x.png"))); // NOI18N
        getContentPane().add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 160));

        rSPanelImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon-secretarial-300x300.png"))); // NOI18N
        getContentPane().add(rSPanelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 160, 160));

        rSPanelImage3.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Video-Game-Controller-Icon-IDV-edit-dark.svg.png"))); // NOI18N
        getContentPane().add(rSPanelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, 140, 140));

        rSPanelImage4.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imagenes/profile_1107725.png"))); // NOI18N
        getContentPane().add(rSPanelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 380, 140, 140));

        btnCerrar.setBackground(new java.awt.Color(204, 0, 0));
        btnCerrar.setText("Cerrar Sesión");
        btnCerrar.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 530, 160, 40));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicio_1.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        veterinaria_alkhovet.JFRegistrar frame = new veterinaria_alkhovet.JFRegistrar();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        veterinaria_alkhovet.JFProductos productos = new veterinaria_alkhovet.JFProductos();
        productos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegosActionPerformed
        veterinaria_alkhovet.JFJuegos juegos = new veterinaria_alkhovet.JFJuegos();
        juegos.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnJuegosActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Veterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Veterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Veterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Veterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Veterinaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnCerrar;
    private rojeru_san.RSButton btnJuegos;
    private rojeru_san.RSButton btnProductos;
    private rojeru_san.RSButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private rojerusan.RSPanelImage rSPanelImage1;
    private rojerusan.RSPanelImage rSPanelImage2;
    private rojerusan.RSPanelImage rSPanelImage3;
    private rojerusan.RSPanelImage rSPanelImage4;
    // End of variables declaration//GEN-END:variables
}
