/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import dao.DAOProducto;
import entidades.ClsProducto;
import java.sql.Date;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import veterinaria_Alkhovet.Veterinaria;

public class JFProducto extends javax.swing.JFrame {

  private List<ClsProducto> productos;
  private DefaultTableModel modelo = new DefaultTableModel();
  private ClsProducto actual;
//  private List<ClsCategoria> categorias;

  /**
   * Creates new form JFProducto
   */
  public JFProducto() {
    initComponents();
    this.activarControles(false);
    this.crearColumnas();
    this.dchFecha.setDate(Date.valueOf(LocalDate.now()));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Categoria = new javax.swing.ButtonGroup();
        panRegistro = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblDescripción = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        spPrecio = new javax.swing.JSpinner();
        txtDescripcion = new javax.swing.JTextField();
        chkVigencia = new javax.swing.JCheckBox();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        rbAlimento = new javax.swing.JRadioButton();
        rbMedicina = new javax.swing.JRadioButton();
        rbAccesorio = new javax.swing.JRadioButton();
        spCantidad = new javax.swing.JSpinner();
        lblCantidad = new javax.swing.JLabel();
        spUnidades = new javax.swing.JSpinner();
        lblUnidades = new javax.swing.JLabel();
        lblPresentacion = new javax.swing.JLabel();
        txtPresentacion = new javax.swing.JTextField();
        dchFecha = new com.toedter.calendar.JDateChooser();
        lblFecha = new javax.swing.JLabel();
        panListado = new javax.swing.JPanel();
        lblProducto = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(970, 380));

        panRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));

        lblNombre.setText("Nombre:");

        lblPrecio.setText("Precio:");

        lblDescripción.setText("Descripción:");

        spPrecio.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        chkVigencia.setText("Vigencia");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        Categoria.add(rbAlimento);
        rbAlimento.setText("Alimento");
        rbAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAlimentoActionPerformed(evt);
            }
        });

        Categoria.add(rbMedicina);
        rbMedicina.setText("Medicina");
        rbMedicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMedicinaActionPerformed(evt);
            }
        });

        Categoria.add(rbAccesorio);
        rbAccesorio.setText("Accesorio");
        rbAccesorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAccesorioActionPerformed(evt);
            }
        });

        spCantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        lblCantidad.setText("Cantidad");

        spUnidades.setModel(new javax.swing.SpinnerNumberModel());

        lblUnidades.setText("Unidades");

        lblPresentacion.setText("Presentacion");

        txtPresentacion.setText(" ");

        dchFecha.setDateFormatString("yyyy/MM/dd");

        lblFecha.setText("Fecha Vencimiento");

        javax.swing.GroupLayout panRegistroLayout = new javax.swing.GroupLayout(panRegistro);
        panRegistro.setLayout(panRegistroLayout);
        panRegistroLayout.setHorizontalGroup(
            panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRegistroLayout.createSequentialGroup()
                .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panRegistroLayout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panRegistroLayout.createSequentialGroup()
                                    .addComponent(rbAlimento)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbMedicina)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbAccesorio))
                                .addGroup(panRegistroLayout.createSequentialGroup()
                                    .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNombre)
                                        .addComponent(lblPrecio)
                                        .addComponent(lblCantidad)
                                        .addComponent(lblFecha)
                                        .addComponent(lblDescripción))
                                    .addGap(28, 28, 28)
                                    .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNombre)
                                        .addGroup(panRegistroLayout.createSequentialGroup()
                                            .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panRegistroLayout.createSequentialGroup()
                                                    .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(spCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                                        .addComponent(spPrecio))
                                                    .addGap(50, 50, 50)
                                                    .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panRegistroLayout.createSequentialGroup()
                                                            .addComponent(lblUnidades)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(spUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(txtPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(dchFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(40, 40, 40))))))
                        .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRegistroLayout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(btnAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar))
                            .addGroup(panRegistroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(chkVigencia)
                                .addGap(275, 275, 275)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRegistroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblPresentacion)
                .addGap(95, 95, 95))
        );
        panRegistroLayout.setVerticalGroup(
            panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRegistroLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAlimento)
                    .addComponent(rbMedicina)
                    .addComponent(rbAccesorio))
                .addGap(26, 26, 26)
                .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUnidades)
                        .addComponent(spUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRegistroLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblPresentacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidad))
                .addGap(29, 29, 29)
                .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha)
                    .addComponent(dchFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addComponent(lblDescripción)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chkVigencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(25, 25, 25))
        );

        panListado.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado"));

        lblProducto.setText("Producto");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblProductos.setModel(this.modelo);
        jScrollPane1.setViewportView(tblProductos);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panListadoLayout = new javax.swing.GroupLayout(panListado);
        panListado.setLayout(panListadoLayout);
        panListadoLayout.setHorizontalGroup(
            panListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListadoLayout.createSequentialGroup()
                .addGroup(panListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panListadoLayout.createSequentialGroup()
                        .addGroup(panListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panListadoLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addGroup(panListadoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE))
                .addContainerGap())
        );
        panListadoLayout.setVerticalGroup(
            panListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnModificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(jButton1)
                        .addGap(82, 82, 82))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      this.activarControles(true);
      this.limpiarControles();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
      this.activarControles(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    public void setFecha(String fecha) {
        
    }
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
      DAOProducto dao;
      ClsProducto prod;
      
      prod = new ClsProducto();
      if (this.rbAlimento.isSelected()==true) {
            prod.setCategoria("Alimento");
        }else if(this.rbMedicina.isSelected()==true) {
            prod.setCategoria("Medicina");
        }else if(this.rbAccesorio.isSelected()==true) {
            prod.setCategoria("Accesorio");
        }
      prod.setNombre(this.txtNombre.getText());
      prod.setPresentacion(this.txtPresentacion.getText());
      prod.setPrecio((double) this.spPrecio.getValue());
      prod.setCantidad((int) this.spCantidad.getValue());
      prod.setUnidades((int) this.spUnidades.getValue());
      prod.setFecha(this.dchFecha.getDate());

      prod.setVigencia(this.chkVigencia.isSelected());
      
//      prod.setCategoria(this.categorias.get(
//              this.cboCategoria.getSelectedIndex()
//              ) );
      
      dao = new DAOProducto();
      try{
        if( this.actual == null){
          dao.registrar(prod);
        }else{
          prod.setCodigo( this.actual .getCodigo());
          dao.actualizar(prod);
        }
        this.activarControles(false);
      }catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
      }finally{
        prod = null;
        dao = null;
      }
      
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
      DAOProducto dao = new DAOProducto();

      try {
        this.productos = dao.listar(
                this.txtProducto.getText());
        this.llenarTabla();
      } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
      } finally {
        dao = null;
      }
    }//GEN-LAST:event_btnBuscarActionPerformed

  private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
    int pos = this.tblProductos.getSelectedRow();
    
    if( pos > -1){
      this.actual = this.productos.get(pos);
      this.presentarDatos();
    }else{
     JOptionPane.showMessageDialog(this, "Debe seleccionar un producto");
    }    
  }//GEN-LAST:event_btnModificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Veterinaria vet =new Veterinaria();
        vet.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAlimentoActionPerformed
        this.lblUnidades.setEnabled(true);
        this.spUnidades.setEnabled(true);
        this.lblPresentacion.setEnabled(true);
        this.txtPresentacion.setEnabled(true);
    }//GEN-LAST:event_rbAlimentoActionPerformed

    private void rbMedicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMedicinaActionPerformed
        this.lblUnidades.setEnabled(true);
        this.spUnidades.setEnabled(true);
        this.lblPresentacion.setEnabled(true);
        this.txtPresentacion.setEnabled(true);
        
    }//GEN-LAST:event_rbMedicinaActionPerformed

    private void rbAccesorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAccesorioActionPerformed
        this.lblUnidades.setEnabled(true);
        this.spUnidades.setEnabled(true);
        this.lblPresentacion.setEnabled(false);
        this.txtPresentacion.setEnabled(false);
        
    }//GEN-LAST:event_rbAccesorioActionPerformed

  private void llenarTabla() {
    this.modelo.setRowCount(0);
    for (ClsProducto producto : productos) {
      this.modelo.addRow(new Object[]{
        producto.getCategoria(),
        producto.getNombre(),
        producto.getFecha(),
//        producto.getCategoria().getNombre(),
        producto.getPrecio(),
        producto.getCantidad(),
        producto.getUnidades(),
        producto.isVigencia(),
//        producto.getCalcularEdad(),
                
      });
    }
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(JFProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(JFProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(JFProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(JFProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new JFProducto().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Categoria;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox chkVigencia;
    private com.toedter.calendar.JDateChooser dchFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDescripción;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPresentacion;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblUnidades;
    private javax.swing.JPanel panListado;
    private javax.swing.JPanel panRegistro;
    private javax.swing.JRadioButton rbAccesorio;
    private javax.swing.JRadioButton rbAlimento;
    private javax.swing.JRadioButton rbMedicina;
    private javax.swing.JSpinner spCantidad;
    private javax.swing.JSpinner spPrecio;
    private javax.swing.JSpinner spUnidades;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPresentacion;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables

  private void activarControles(boolean estado) {
    this.panRegistro.setEnabled(estado);
    this.rbAlimento.setEnabled(estado);
    this.rbMedicina.setEnabled(estado);
    this.rbAccesorio.setEnabled(estado);
    this.lblDescripción.setEnabled(estado);
    this.lblNombre.setEnabled(estado);
    this.lblPresentacion.setEnabled(estado);
    this.lblPrecio.setEnabled(estado);
    this.lblUnidades.setEnabled(estado);
    this.lblCantidad.setEnabled(estado);
    this.btnAceptar.setEnabled(estado);
    this.lblFecha.setEnabled(estado);
    this.dchFecha.setEnabled(estado);
    this.btnCancelar.setEnabled(estado);
    this.txtDescripcion.setEnabled(estado);
    this.txtNombre.setEnabled(estado);
    this.txtPresentacion.setEnabled(estado);
    this.spPrecio.setEnabled(estado);
    this.spCantidad.setEnabled(estado);
    this.spUnidades.setEnabled(estado);
    this.chkVigencia.setEnabled(estado);

    this.lblProducto.setEnabled(!estado);
    this.txtProducto.setEnabled(!estado);
    this.btnNuevo.setEnabled(!estado);
    this.btnModificar.setEnabled(!estado);
    this.btnBuscar.setEnabled(!estado);
    this.tblProductos.setEnabled(!estado);
    this.panListado.setEnabled(!estado);

    if (estado == true) {
      this.rbAlimento.requestFocusInWindow();
    } else {
      this.btnBuscar.requestFocusInWindow();
    }
  }

  private void limpiarControles() {
    SpinnerNumberModel modelo = new SpinnerNumberModel();
    SpinnerNumberModel modelo2 = new SpinnerNumberModel();
    SpinnerNumberModel modelo3 = new SpinnerNumberModel();
    
//    this.cboCategoria.setSelectedIndex(-1);
    this.rbAlimento.setSelected(false);
    this.rbMedicina.setSelected(false);
    this.rbAccesorio.setSelected(false);
    
    this.txtNombre.setText("");
    this.txtPresentacion.setText("");

    modelo = (SpinnerNumberModel) this.spPrecio.getModel();
    this.spPrecio.setValue(modelo.getMinimum());

    modelo2 = (SpinnerNumberModel) this.spCantidad.getModel();
    this.spCantidad.setValue(modelo.getMinimum());

    modelo3 = (SpinnerNumberModel) this.spUnidades.getModel();
    this.spUnidades.setValue(modelo.getMinimum());
    this.dchFecha.setDate(Date.valueOf(LocalDate.now()));
    this.txtDescripcion.setText("");
    this.chkVigencia.setSelected(false);
  }

  private void crearColumnas() {
    this.modelo.addColumn("Categoria");
    this.modelo.addColumn("Nombre");
    this.modelo.addColumn("Fecha");
    this.modelo.addColumn("Precio");
    this.modelo.addColumn("Cantidad");
    this.modelo.addColumn("Unidad");
    this.modelo.addColumn("Vigencia");
  }

//  private ComboBoxModel cargarCategorias() {
//    DAOCategoria dao = new DAOCategoria();
//    DefaultComboBoxModel modelo = new DefaultComboBoxModel<>();
//
//    try {
//      this.categorias = dao.listar();
//      this.llenarCombo(modelo);
//    } catch (Exception e) {
//      JOptionPane.showMessageDialog(this, e.getMessage());
//    } finally {
//      dao = null;
//    }
//
//    return modelo;
//  }

//  private void llenarCombo(DefaultComboBoxModel modelo) {
//    for (ClsCategoria cat : this.categorias) {
//      modelo.addElement(cat.getNombre());
//    }
//  }

  private void presentarDatos() {
    DAOProducto dao = new DAOProducto();
    
    try{
      this.actual = dao.leer( this.actual);
      if( this.actual != null){
//        this.cboCategoria.setSelectedIndex(
//                this.buscarCategoria( this.actual.getCategoria() )
//          );

        if (this.rbAlimento.isSelected()==true) {
                this.rbAlimento.setSelected(true);
            }else if((this.rbMedicina.isSelected()==true)) {
                this.rbMedicina.setSelected(true);
            }else if((this.rbAccesorio.isSelected()==true)) {
                this.rbAccesorio.setSelected(true);}
                
        this.txtNombre.setText(this.actual.getNombre());
        this.txtPresentacion.setText(this.actual.getPresentacion());
        this.spPrecio.setValue(this.actual.getPrecio());
        this.spCantidad.setValue(this.actual.getCantidad());
        this.spUnidades.setValue(this.actual.getUnidades());
        this.dchFecha.setDate(this.actual.getFecha());
        this.txtDescripcion.setText(this.actual.getDescripcion());
        this.chkVigencia.setSelected(this.actual.isVigencia());
        this.activarControles(true);
      }else{
        JOptionPane.showMessageDialog(this, 
                "No se encontró el producto buscado");
      }
    }catch(Exception e){
      JOptionPane.showMessageDialog(this, e.getMessage());
    }finally{
      dao = null;
    }
  }

//  private int buscarCategoria(ClsCategoria buscado) {
//    int i=0;
//    
//    for (ClsCategoria cat : this.categorias) {
//      if( cat.getCodigo() == buscado.getCodigo() ){
//        return i;
//      }
//      i++;
//    }
//    
//    return -1;
//  }

}
