/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;
import dao.DAOProveedor;
import entidades.ClsProveedor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import veterinaria_Alkhovet.Veterinaria;

/**
 *
 * @author USUARIO
 */
public class JFProveedor extends javax.swing.JFrame {
    private DefaultTableModel modelo=new DefaultTableModel();
    private ClsProveedor actual;
    private List<ClsProveedor> proveedores;
    /**
     * Creates new form JFProveedor
     */
    public JFProveedor() {
        initComponents();
        this.activarControles(false);
        this.crearColumnas();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panParte1 = new javax.swing.JPanel();
        lblRazonSocial = new javax.swing.JLabel();
        lblRuc = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        txtRuc = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        chkVigencia = new javax.swing.JCheckBox();
        lblRepresentante = new javax.swing.JLabel();
        txtRepresentante = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        panParte2 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActualizar = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panParte1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblRazonSocial.setText("Razon Social");

        lblRuc.setText("Ruc");

        lblTelefono.setText("Telefono");

        lblCorreo.setText("Correo");

        txtRazonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRazonSocialKeyTyped(evt);
            }
        });

        txtRuc.setText(" ");
        txtRuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRucKeyTyped(evt);
            }
        });

        txtTelefono.setText(" ");
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        txtCorreo.setText(" ");
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        chkVigencia.setText("Vigencia");

        lblRepresentante.setText("Representante");

        lblDireccion.setText("Direccion");

        txtDireccion.setText(" ");

        javax.swing.GroupLayout panParte1Layout = new javax.swing.GroupLayout(panParte1);
        panParte1.setLayout(panParte1Layout);
        panParte1Layout.setHorizontalGroup(
            panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panParte1Layout.createSequentialGroup()
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panParte1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnAceptar)
                        .addGap(43, 43, 43)
                        .addComponent(btnCancelar))
                    .addGroup(panParte1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRepresentante)
                            .addComponent(lblTelefono)
                            .addComponent(chkVigencia)
                            .addComponent(lblDireccion)
                            .addComponent(lblRazonSocial)
                            .addComponent(lblRuc)
                            .addComponent(lblCorreo))
                        .addGap(18, 18, 18)
                        .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        panParte1Layout.setVerticalGroup(
            panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panParte1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazonSocial)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRepresentante)
                    .addComponent(txtRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRuc)
                    .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkVigencia)
                .addGap(28, 28, 28)
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panParte2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        tblActualizar.setModel(this.modelo);
        jScrollPane1.setViewportView(tblActualizar);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panParte2Layout = new javax.swing.GroupLayout(panParte2);
        panParte2.setLayout(panParte2Layout);
        panParte2Layout.setHorizontalGroup(
            panParte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panParte2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panParte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panParte2Layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addGap(38, 38, 38)
                        .addComponent(btnModificar))
                    .addComponent(btnActualizar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panParte2Layout.setVerticalGroup(
            panParte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panParte2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(panParte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnModificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROVEEDOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panParte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panParte2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panParte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panParte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
            this.actual= null;
            this.limpiarControles();
            this.activarControles(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
                   ClsProveedor prov;
                   DAOProveedor dao;
        if (this.validarDatos()== true) {       
           prov = new ClsProveedor(); 
            
        prov.setRazon_Social(this.txtRazonSocial.getText());
        prov.setRepresentante(this.txtRepresentante.getText());
        prov.setRuc(this.txtRuc.getText());
        prov.setTelefono(this.txtTelefono.getText());
        prov.setCorreo(this.txtCorreo.getText());
        prov.setDireccion(this.txtDireccion.getText());
        prov.setVigencia(this.chkVigencia.isSelected());
    
        dao = new DAOProveedor();
      try{
        if( this.actual == null){
          dao.registrar(prov);
        }else{
          prov.setCodigo( this.actual .getCodigo());
          dao.actualizar(prov);
        }
        this.activarControles(false);
      }catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
      }finally{
        prov = null;
        dao = null;
      }
              this.activarControles(false);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
             this.activarControles(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
             DAOProveedor dao = new DAOProveedor();
       
       try{
           this.proveedores = dao.listar();
           this.llenarTabla();
       }catch (Exception e){
           JOptionPane.showMessageDialog(this, e.getMessage());
       }finally{
           dao = null;
       }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
           int pos = this.tblActualizar.getSelectedRow();
    
        if(pos > -1){
          this.actual = this.proveedores.get(pos);
          this.presentarDatos();
          this.activarControles(true);
        }else{
         JOptionPane.showMessageDialog(this, "Debe seleccionar un producto");
         this.tblActualizar.requestFocusInWindow();
        } 
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        Veterinaria principal = new Veterinaria();
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtRucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucKeyTyped
        int caracteres=11;
        if (this.txtRuc.getText().length()>=caracteres) {
            evt.consume();
        }
        char c= evt.getKeyChar();
        if (c<'0' || c> '9') evt.consume(); {

        }
    }//GEN-LAST:event_txtRucKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
               int caracteres=9;
        if (this.txtTelefono.getText().length()>=caracteres) {
            evt.consume();
        }
        char c= evt.getKeyChar();
        if (c<'0' || c> '9') evt.consume(); {

        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtRazonSocialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonSocialKeyTyped
        char c = evt.getKeyChar();
        
        if ((c<'a' || c>'z') && (c<'A' || c>'Z') ) evt.consume();
    }//GEN-LAST:event_txtRazonSocialKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox chkVigencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JLabel lblRepresentante;
    private javax.swing.JLabel lblRuc;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel panParte1;
    private javax.swing.JPanel panParte2;
    private javax.swing.JTable tblActualizar;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtRepresentante;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void activarControles(boolean estado) {
        this.panParte1.setEnabled(estado);
        this.lblRazonSocial.setEnabled(estado);
        this.txtRazonSocial.setEnabled(estado);
        this.lblRepresentante.setEnabled(estado);
        this.txtRepresentante.setEnabled(estado);
        this.lblRuc.setEnabled(estado);
        this.txtRuc.setEnabled(estado);
        this.lblTelefono.setEnabled(estado);
        this.txtTelefono.setEnabled(estado);
        this.lblCorreo.setEnabled(estado);
        this.txtCorreo.setEnabled(estado);
        this.lblDireccion.setEnabled(estado);
        this.txtDireccion.setEnabled(estado);
        this.chkVigencia.setEnabled(estado);
        this.btnAceptar.setEnabled(estado);
        this.btnCancelar.setEnabled(estado);
        
        this.panParte2.setEnabled(!estado);
        this.btnActualizar.setEnabled(!estado);
        this.tblActualizar.setEnabled(!estado);
        this.btnNuevo.setEnabled(!estado);
        this.btnModificar.setEnabled(!estado);
        
        if (estado==true) {
                this.txtRazonSocial.requestFocusInWindow();
        }else{
            this.btnActualizar.requestFocusInWindow();
        }
    }

    private void limpiarControles() {
       this.txtRazonSocial.setText("");
       this.txtRepresentante.setText("");
        this.txtRuc.setText("");
        this.txtTelefono.setText("");
        this.txtCorreo.setText("");
        this.txtDireccion.setText("");
        this.chkVigencia.setSelected(true);
    }

    private void presentarDatos() {
       this.txtRazonSocial.setText(this.actual.getRazon_Social());
       this.txtRepresentante.setText(this.actual.getRepresentante());
        this.txtRuc.setText(this.actual.getRuc());
        this.txtTelefono.setText(this.actual.getTelefono());
        this.txtCorreo.setText(this.actual.getCorreo());
        this.txtRepresentante.setText(this.actual.getRepresentante());
          this.chkVigencia.setSelected(this.actual.isVigencia());
    }

    private void crearColumnas() {
            this.modelo.addColumn("Razon Social");
            this.modelo.addColumn("Representante");
            this.modelo.addColumn("Ruc");
            this.modelo.addColumn("Telefono");
            this.modelo.addColumn("Correo");
            this.modelo.addColumn("Direccion");
            this.modelo.addColumn("Vigencia");
            
    }

    private boolean validarDatos() {
       boolean validar=true;
           if (txtRazonSocial.getText().isEmpty()) {
               JOptionPane.showMessageDialog(null, "Ingrese Razon Social","error", JOptionPane.ERROR_MESSAGE);}
           else if (txtRepresentante.getText().isEmpty()) {
               JOptionPane.showMessageDialog(null, "Ingrese Representante","error", JOptionPane.ERROR_MESSAGE);}
           else if (txtRuc.getText().isEmpty()) {
               JOptionPane.showMessageDialog(null, "Ingrese RUC","error", JOptionPane.ERROR_MESSAGE);}
           else if (txtTelefono.getText().isEmpty()) {
               JOptionPane.showMessageDialog(null, "Ingrese Telefono","error", JOptionPane.ERROR_MESSAGE);}
           else if (txtCorreo.getText().isEmpty()) {
               JOptionPane.showMessageDialog(null, "Ingrese Correo","error", JOptionPane.ERROR_MESSAGE);}
           else if (txtDireccion.getText().isEmpty()) {
               JOptionPane.showMessageDialog(null, "Ingrese Direccion","error", JOptionPane.ERROR_MESSAGE);}
        return validar;
    }

    private void llenarTabla() {
        this.modelo.setRowCount(0);
      if (this.proveedores != null) {
         for (ClsProveedor proveedor : proveedores) {
        this.modelo.addRow(new Object[]{
        proveedor.getRazon_Social(),
        proveedor.getRepresentante(),
        proveedor.getRuc(),
        proveedor.getTelefono(),
        proveedor.getCorreo(),
        proveedor.getDireccion(),
        proveedor.isVigencia()
      });
      }
    }
        
    }
}
