/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import dao.DAOVeterinario;
import entidades.ClsVeterinario;
import java.sql.Date;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import veterinaria_Alkhovet.Veterinaria;

/**
 *
 * @author USUARIO
 */
public class JFVeterinario extends javax.swing.JFrame {
    private DefaultTableModel modelo =new DefaultTableModel();
    private ClsVeterinario actual;
    private List<ClsVeterinario> veterinarios;

    /**
     * Creates new form JFVeterinario
     */
    public JFVeterinario() {
        initComponents();
        this.crearColumnas();
        this.activarControles(false);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        panParte1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        chkVigencia = new javax.swing.JCheckBox();
        rbFemenino = new javax.swing.JRadioButton();
        rbMasculino = new javax.swing.JRadioButton();
        dchFechaNacimiento = new com.toedter.calendar.JDateChooser();
        lblFechaNacimiento = new javax.swing.JLabel();
        panParte2 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActualizar = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panParte1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblNombre.setText("Nombre");

        lblApellido.setText("Apellido");

        lblDNI.setText("DNI");

        lblTelefono.setText("Telefono");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNIKeyTyped(evt);
            }
        });

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        chkVigencia.setText("Vigencia");

        bgSexo.add(rbFemenino);
        rbFemenino.setText("Femenino");

        bgSexo.add(rbMasculino);
        rbMasculino.setText("Masculino");

        lblFechaNacimiento.setText("Fecha nacimiento");

        javax.swing.GroupLayout panParte1Layout = new javax.swing.GroupLayout(panParte1);
        panParte1.setLayout(panParte1Layout);
        panParte1Layout.setHorizontalGroup(
            panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panParte1Layout.createSequentialGroup()
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panParte1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panParte1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblTelefono)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefono))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panParte1Layout.createSequentialGroup()
                                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panParte1Layout.createSequentialGroup()
                                        .addComponent(rbFemenino)
                                        .addGap(22, 22, 22)
                                        .addComponent(rbMasculino))
                                    .addComponent(chkVigencia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panParte1Layout.createSequentialGroup()
                                        .addComponent(lblFechaNacimiento)
                                        .addGap(18, 18, 18)
                                        .addComponent(dchFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panParte1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnAceptar)
                        .addGap(59, 59, 59)
                        .addComponent(btnCancelar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panParte1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblApellido))
                    .addComponent(lblDNI))
                .addGap(36, 36, 36)
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtApellido)
                    .addComponent(txtNombre))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        panParte1Layout.setVerticalGroup(
            panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panParte1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDNI)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dchFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaNacimiento))
                .addGap(18, 18, 18)
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMasculino)
                    .addComponent(rbFemenino))
                .addGap(18, 18, 18)
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkVigencia)
                .addGap(18, 18, 18)
                .addGroup(panParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        tblActualizar.setModel(this.modelo);
        jScrollPane1.setViewportView(tblActualizar);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panParte2Layout = new javax.swing.GroupLayout(panParte2);
        panParte2.setLayout(panParte2Layout);
        panParte2Layout.setHorizontalGroup(
            panParte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panParte2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panParte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panParte2Layout.createSequentialGroup()
                        .addGroup(panParte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panParte2Layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addGap(32, 32, 32)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCerrar))
                            .addGroup(panParte2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panParte2Layout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panParte2Layout.setVerticalGroup(
            panParte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panParte2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(panParte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnModificar)
                    .addComponent(btnCerrar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VETERINARIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panParte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panParte2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addComponent(panParte2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panParte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
            this.actual=null;
            this.limpiarControles();
            this.activarControles(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       DAOVeterinario dao = new DAOVeterinario();
       
       try{
           this.veterinarios = dao.listar();
           this.llenarTabla();
       }catch (Exception e){
           JOptionPane.showMessageDialog(this, e.getMessage());
       }finally{
           dao = null;
       }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
             int pos = this.tblActualizar.getSelectedRow();
    
    /*  Cuando le das al boton
        1. No te aparecen los datos correctos en el panel 1
        2. duplica la columna en el listado en el panel 2
    */
             
        if(pos > -1){
          this.actual = this.veterinarios.get(pos);
          this.presentarDatos();
          this.activarControles(true);
        }else{
         JOptionPane.showMessageDialog(this, "Debe seleccionar un producto");
         this.tblActualizar.requestFocusInWindow();
        } 
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        Veterinaria principal = new Veterinaria();
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.activarControles(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        DAOVeterinario dao;
        ClsVeterinario vet;

        if (this.validarDatos()== true) {
            
            vet = new ClsVeterinario();
            vet.setNombre(this.txtNombre.getText());
            vet.setApellido(this.txtApellido.getText());
            vet.setDni(this.txtDNI.getText());
            vet.setFechaNacimiento(this.dchFechaNacimiento.getDate());
            if (this.rbFemenino.isSelected()==true) {
            vet.setSexo("F");
        }else if(this.rbMasculino.isSelected()==true) {
            vet.setSexo("M");
        }

            vet.setTelefono(this.txtTelefono.getText());

            if (this.chkVigencia.isSelected()== true) {
                vet.setVigencia(true);
        }else{
                vet.setVigencia(false);
             }

                dao = new DAOVeterinario();
            try {
                if( this.actual == null){
         dao.registrar(vet);
                }else{
                      vet.setCodigoVet(this.actual .getCodigoVet());
         dao.actualizar(vet);
                     }
        this.activarControles(false);
                }catch(Exception e){
                     JOptionPane.showMessageDialog(this, e.getMessage());
            }finally{
                vet = null;
                dao = null;
      }
                this.activarControles(false);
            }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        int caracteres=9;
        if (this.txtTelefono.getText().length()>=caracteres) {
            evt.consume();
        }
        char c= evt.getKeyChar();
        if (c<'0' || c> '9') evt.consume(); {

        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyTyped
        int caracteres=8;
        if (this.txtDNI.getText().length()>=caracteres) {
            evt.consume();
        }
        char c= evt.getKeyChar();
        if (c<'0' || c> '9') evt.consume(); {

        }
    }//GEN-LAST:event_txtDNIKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        char c = evt.getKeyChar();

        if ((c<'a' || c>'z') && (c<'A' || c>'Z') ) evt.consume();
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();

        if ((c<'a' || c>'z') && (c<'A' || c>'Z') ) evt.consume();
    }//GEN-LAST:event_txtNombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVeterinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox chkVigencia;
    private com.toedter.calendar.JDateChooser dchFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel panParte1;
    private javax.swing.JPanel panParte2;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTable tblActualizar;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void activarControles(boolean estado) {
        this.panParte1.setEnabled(estado);
        this.lblNombre.setEnabled(estado);
        this.txtNombre.setEnabled(estado);
        this.lblApellido.setEnabled(estado);
        this.txtApellido.setEnabled(estado);
        this.lblDNI.setEnabled(estado);
        this.txtDNI.setEnabled(estado);
        this.lblFechaNacimiento.setEnabled(estado);
        this.dchFechaNacimiento.setEnabled(estado);
        this.rbFemenino.setEnabled(estado);
        this.rbMasculino.setEnabled(estado);
        this.lblTelefono.setEnabled(estado);
        this.txtTelefono.setEnabled(estado);
        this.chkVigencia.setEnabled(estado);
        this.btnAceptar.setEnabled(estado);
        this.btnCancelar.setEnabled(estado);
        
        this.panParte2.setEnabled(!estado);
        this.btnActualizar.setEnabled(!estado);
        this.tblActualizar.setEnabled(!estado);
        this.btnNuevo.setEnabled(!estado);
        this.btnModificar.setEnabled(!estado);
        this.btnCerrar.setEnabled(!estado);
                
        if (estado== true) {
            this.txtNombre.requestFocusInWindow();
        }else{
            this.btnActualizar.requestFocusInWindow();
        }
    }

    private void limpiarControles() {
        this.txtNombre.requestFocusInWindow();
        this.txtNombre.setText("");
        this.txtApellido.setText("");
        this.txtDNI.setText("");
        this.dchFechaNacimiento.setDate(Date.valueOf(LocalDate.now()));
        this.rbFemenino.setSelected(true);
        this.txtTelefono.setText("");
        this.chkVigencia.setSelected(false);
     
    }

    private void presentarDatos() {
        DAOVeterinario dao = new DAOVeterinario();
        try{
            this.actual = dao.leer(this.actual);
            if (this.actual != null) {
                this.dchFechaNacimiento.setDate(Date.valueOf(LocalDate.now()));
              this.txtNombre.setText(this.actual.getNombre());
              this.txtApellido.setText(this.actual.getApellido());
              this.txtDNI.setText(this.actual.getDni());
        
            if (this.rbFemenino.isSelected()==true) {
                this.rbFemenino.setText("F");
            }else if(this.rbMasculino.isSelected()==true) {
                this.rbMasculino.setText("M");
            }
       
             this.txtTelefono.setText(this.actual.getTelefono());
             this.chkVigencia.setSelected(this.actual.isVigencia());  
            }else{
                JOptionPane.showMessageDialog(this, "El veterinarie solicitade no se encuentra");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }finally{
            dao = null;
        }
    }

    private void crearColumnas() {
            this.modelo.addColumn("Nombre");
            this.modelo.addColumn("Apellido");
            this.modelo.addColumn("DNI");
            this.modelo.addColumn("Fecha Nacimiento");
            this.modelo.addColumn("Sexo");
            this.modelo.addColumn("Telefono");
            this.modelo.addColumn("Vigencia");
    }
    
    private void llenarTabla() {
        this.modelo.setRowCount(0);
      if (this.veterinarios != null) {
         for (ClsVeterinario veterinario : veterinarios) {
        this.modelo.addRow(new Object[]{
        veterinario.getNombre(),
        veterinario.getApellido(),
        veterinario.getDni(),
        veterinario.getFechaNacimiento(),
        veterinario.getSexo(),
        veterinario.getTelefono(),
        veterinario.isVigencia()
      });
      }
    }
  }

    private boolean validarDatos() {
        boolean validar=true;
           if (txtNombre.getText().isEmpty()) {
               JOptionPane.showMessageDialog(null, "Ingrese Nombre","error", JOptionPane.ERROR_MESSAGE);}
           else if (txtApellido.getText().isEmpty()) {
               JOptionPane.showMessageDialog(null, "Ingrese Apellido","error", JOptionPane.ERROR_MESSAGE);}
           else if (txtDNI.getText().isEmpty()) {
               JOptionPane.showMessageDialog(null, "Ingrese DNI","error", JOptionPane.ERROR_MESSAGE);}
           else if (txtTelefono.getText().isEmpty()) {
               JOptionPane.showMessageDialog(null, "Ingrese Telefono","error", JOptionPane.ERROR_MESSAGE);}
        return validar;
    }

    
}
